CFLAGS=-Wall -Wextra -g


all: simultane successif

simultane: simultane.o
simultane.o: simultane.c simultane.h

successif: successif.o
successif.o: successif.c successif.h


clean: 
	rm -rf *.o simultane successif