CFLAGS=-Wall -Wextra -g


all: simultane successif miniature

simultane: simultane.o
simultane.o: simultane.c simultane.h

successif: successif.o
successif.o: successif.c successif.h

miniature: miniature.o
miniature.o: miniature.c miniature.h

clean: 
	rm -rf *.o simultane successif